### ISSUE TITLE
Nearest to avg

### ISSUE THREAD

**Issue by emrerenJs** [HusnaSari/Algorithms#4]

**Comment by emrerenJs** [comment]
- Define 10 length sized integer array
- Read 10 integer number from console.
- Find the mean of array
- Find the nearest element to mean in the array.
- Print nearest element and element  index to screen.

For example: [1,2,3,4,5,6,7,8,9,10]
Output : Index : 4, element : 5

Difficulty : 10/4

**Comment by HusnaSari** [comment]
Eta: 30 minute

**Comment by HusnaSari** [comment]
Ata: 1 hour
