### ISSUE TITLE
Half Number Pyramiths

### ISSUE THREAD

**Issue by emrerenJs** [HusnaSari/Algorithms#7]
Write a program that gives a half pyramid of increasing numbers.

- Read N value from console input
- Write increasing numbers up to N rows.

Example 1 : 
```
N : 4
Output : 
1 (row 1)
2 3 (row : 2)
4 5 6 (row : 3)
7 8 9 10 (row : 4)
```

Example 2 : 
```
N : 6
Output : 
1
2 3
4 5 6
7 8 9 10
11 12 13 14 15
16 17 18 19 20 21
```

Difficulty: 10/5

**Comment by HusnaSari** [comment]
Eta: 1 hour

**Comment by HusnaSari** [comment]
Ata: 1hour
